apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onetimesecret-chart.onetimesecret.fullname" . }}
  labels:
    app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
    spec:
      containers:
      - name: onetimesecret
        image: {{ .Values.onetimesecret.image }}
        ports:
        - containerPort: {{ .Values.onetimesecret.service.port }}
        env:
        - name: REDIS_URL
          value: {{ .Values.onetimesecret.env.REDIS_URL }}
        - name: COLONEL
          value: {{ .Values.onetimesecret.env.COLONEL }}
        - name: HOST
          value: {{ .Values.onetimesecret.env.HOST }}
        - name: SSL
          value: "{{ .Values.onetimesecret.env.SSL }}"  # Ensure this is quoted
