apiVersion: v1
kind: Service
metadata:
  name: {{ include "onetimesecret-chart.onetimesecret.fullname" . }}
spec:
  selector:
    app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.onetimesecret.service.port }}
    targetPort: {{ .Values.onetimesecret.service.port }}
  type: {{ .Values.onetimesecret.service.type }}
